philosophical_phrases = [
    {"phrase": "The only constant in life is change.", "author": "Heraclitus"},
    {"phrase": "To live is the rarest thing in the world. Most people exist, that is all.", "author": "Oscar Wilde"},
    {"phrase": "The mind is everything. What you think, you become.", "author": "Buddha"},
    {"phrase": "Life is really simple, but we insist on making it complicated.", "author": "Confucius"},
    {"phrase": "The purpose of our lives is to be happy.", "author": "Dalai Lama"},
    {"phrase": "The greatest glory in living lies not in never falling, but in rising every time we fall.", "author": "Nelson Mandela"},
    {"phrase": "In three words I can sum up everything I've learned about life: it goes on.", "author": "Robert Frost"},
    {"phrase": "The only way to do great work is to love what you do.", "author": "Steve Jobs"},
    {"phrase": "We are what we repeatedly do. Excellence, then, is not an act but a habit.", "author": "Aristotle"},
    {"phrase": "Life is short, and it's up to you to make it sweet.", "author": "Sarah Louise Delany"},
    {"phrase": "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.", "author": "Ralph Waldo Emerson"},
    {"phrase": "You don't have to be rich to sparkle.", "author": "Unknown"},
    {"phrase": "It is not enough to be busy; so are the ants. The question is: What are we busy about?", "author": "Henry David Thoreau"},
    {"phrase": "The only limit to our realization of tomorrow will be our doubts of today.", "author": "Franklin D. Roosevelt"},
    {"phrase": "Success is not final, failure is not fatal: It is the courage to continue that counts.", "author": "Winston Churchill"},
    {"phrase": "The best way to predict the future is to create it.", "author": "Peter Drucker"},
    {"phrase": "Life is what happens when you're busy making other plans.", "author": "John Lennon"},
    {"phrase": "The purpose of human life is to serve and to show compassion and the will to help others.", "author": "Albert Schweitzer"},
    {"phrase": "Believe you can and you're halfway there.", "author": "Theodore Roosevelt"},
    {"phrase": "Do not take life too seriously. You will never get out of it alive.", "author": "Elbert Hubbard"},
    {"phrase": "The only way to do great work is to love what you do.", "author": "Steve Jobs"},
    {"phrase": "In the middle of difficulty lies opportunity.", "author": "Albert Einstein"},
    {"phrase": "The best revenge is to be unlike him who performed the injustice.", "author": "Marcus Aurelius"},
    {"phrase": "Don't cry because it's over, smile because it happened.", "author": "Dr. Seuss"},
    {"phrase": "Be the change that you wish to see in the world.", "author": "Mahatma Gandhi"},
    {"phrase": "The only constant in life is change.", "author": "Heraclitus"},
    {"phrase": "To live is the rarest thing in the world. Most people exist, that is all.", "author": "Oscar Wilde"},
    {"phrase": "The mind is everything. What you think, you become.", "author": "Buddha"},
    {"phrase": "Life is really simple, but we insist on making it complicated.", "author": "Confucius"},
    {"phrase": "The purpose of our lives is to be happy.", "author": "Dalai Lama"},
    {"phrase": "The greatest glory in living lies not in never falling, but in rising every time we fall.", "author": "Nelson Mandela"},
    {"phrase": "In three words I can sum up everything I've learned about life: it goes on.", "author": "Robert Frost"},
    {"phrase": "The only way to do great work is to love what you do.", "author": "Steve Jobs"},
    {"phrase": "We are what we repeatedly do. Excellence, then, is not an act but a habit.", "author": "Aristotle"},
    {"phrase": "Life is short, and it's up to you to make it sweet.", "author": "Sarah Louise Delany"},
    {"phrase": "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.", "author": "Ralph Waldo Emerson"},
    {"phrase": "You don't have to be rich to sparkle.", "author": "Unknown"},
    {"phrase": "It is not enough to be busy; so are the ants. The question is: What are we busy about?", "author": "Henry David Thoreau"},
    {"phrase": "The only limit to our realization of tomorrow will be our doubts of today.", "author": "Franklin D. Roosevelt"},
    {"phrase": "Success is not final, failure is not fatal: It is the courage to continue that counts.", "author": "Winston Churchill"},
    {"phrase": "The best way to predict the future is to create it.", "author": "Peter Drucker"},
    {"phrase": "Life is what happens when you're busy making other plans.", "author": "John Lennon"},
    {"phrase": "The purpose of human life is to serve and to show compassion and the will to help others.", "author": "Albert Schweitzer"},
    {"phrase": "Believe you can and you're halfway there.", "author": "Theodore Roosevelt"},
    {"phrase": "Do not take life too seriously. You will never get out of it alive.", "author": "Elbert Hubbard"},
    {"phrase": "The only way to do great work is to love what you do.", "author": "Steve Jobs"},
    {"phrase": "In the middle of difficulty lies opportunity.", "author": "Albert Einstein"},
    {"phrase": "The best revenge is to be unlike him who performed the injustice.", "author": "Marcus Aurelius"},
    {"phrase": "Don't cry because it's over, smile because it happened.", "author": "Dr. Seuss"},
    {"phrase": "Be the change that you wish to see in the world.", "author": "Mahatma Gandhi"},
]